export const stockSymbols = [
    { symbol: "JPM", name: "JPMorgan Chase & Co." },
    { symbol: "BAC", name: "Bank of America Corp." },
    { symbol: "WFC", name: "Wells Fargo & Co." },
    { symbol: "C", name: "Citigroup Inc." },
    { symbol: "GS", name: "Goldman Sachs Group Inc." },
    { symbol: "MS", name: "Morgan Stanley" },
    { symbol: "AXP", name: "American Express Co." },
    { symbol: "USB", name: "U.S. Bancorp" },
    { symbol: "PNC", name: "PNC Financial Services Group" },
    { symbol: "BK", name: "Bank of New York Mellon Corp." },
    { symbol: "SCHW", name: "Charles Schwab Corp." },
    { symbol: "BLK", name: "BlackRock Inc." },
    { symbol: "TFC", name: "Truist Financial Corp." },
    { symbol: "COF", name: "Capital One Financial Corp." },
    { symbol: "AIG", name: "American International Group Inc." },
    { symbol: "CB", name: "Chubb Limited" },
    { symbol: "PRU", name: "Prudential Financial Inc." },
    { symbol: "MET", name: "MetLife Inc." },
    { symbol: "ALL", name: "Allstate Corp." },
    { symbol: "TRV", name: "Travelers Companies Inc." },
    { symbol: "STT", name: "State Street Corp." },
  ];
  